### ISSUE TITLE
Cannot connect to an AWS cluster

### ISSUE THREAD

**Issue by ffissore** [loop-os/katapult#52]
I have set up a k8s cluster in AWS, under an AWS role
`kubectl` is correctly configured and I can access cluster resources, for example
```
federico@pawa:~$ kubectl get svc
NAME            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
kubernetes      ClusterIP   10.100.0.1       <none>        443/TCP    2d1h
```

When attempting to deploy using katapult, I get an Unauthorized error (getting such error requires #48 to be merged)

```
federico@pawa:$ KATAPULT_KUBE_CONFIG=$(cat ~/.kube/config) AWS_ACCESS_KEY_ID=... AWS_SECRET_ACCESS_KEY=... KATAPULT_KUBE_NAMESPACE=default katapult deploy -t kubernetes -e my-product
kubernetes-client deprecated require('kubernetes-client').config, use require('kubernetes-client/backends/request').config. ../../katapult/src/lib/kubernetes.ts:73:53
kubernetes-client deprecated fromKubeconfig see https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md#request-kubeconfig- ../../katapult/src/lib/kubernetes.ts:73:60
kubernetes-client deprecated Client({ config }), see https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md ../../katapult/src/lib/kubernetes.ts:72:36
kubernetes-client deprecated Request() without a .kubeconfig option, see https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md ../../katapult/node_modules/kubernetes-client/lib/swagger-client.js:200:19
Error: Unauthorized
    at ~/materiale/works_Balena/katapult/node_modules/kubernetes-client/backends/request/client.js:225:25
    at Request._callback (~/materiale/works_Balena/katapult/node_modules/kubernetes-client/backends/request/client.js:156:22)
    at Request.self.callback (~/materiale/works_Balena/katapult/node_modules/request/request.js:185:22)
    at Request.<anonymous> (~/materiale/works_Balena/katapult/node_modules/request/request.js:1161:10)
    at IncomingMessage.<anonymous> (~/materiale/works_Balena/katapult/node_modules/request/request.js:1083:12)
```

At at a first glace, my `~/.kube/config` is different than a normal, non-AWS one, as the `user` section has an `exec` child. However, npm module kubernetes-client [knows about exec](https://github.com/godaddy/kubernetes-client/blob/master/backends/request/config.js#L83) and [how to deal with it](https://github.com/godaddy/kubernetes-client/blob/master/backends/request/auth-providers/cmd.js)

I haven't found the root cause but I have a workaround.
- with `~/.kube/config` unchanged, open a terminal and run `kubectl proxy --port=8080`: this will create a local, non authenticated endpoint
- edit `~/.kube/config`, changing the value of `server` to `http://localhost:8080`
- re-run katapult, which will know succeed

It's crucial that `kubectl proxy` is run with the original value of `server`, otherwise it will enter an endless loop and fail

**Comment by ffissore** [comment]
After much digging and monkey patching, the workaround is to edit `~/.kube/config` and ensure that `users.user.exec.args` array include 
```yaml
- --profile
- '<NAME OF THE AWS ROLE PROFILE>'
```

In my katapult invocation from above, you can see I'm specifying both `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`. Apparently this makes `aws` cli ignore the value of `AWS_PROFILE` when generating a token with `aws eks get-token`, which is the command mentioned in `~/.kube/config` which was generated by `aws eks update-kubeconfig` (see [docs](https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html))
However I do need to specify the AWS access key as they are needed by my deployment templates.
By editing `~/.kube/config` as described, I can force `aws` cli to use the specified profile and thus authenticate successfully

PS: I tried fixing this in npm module kubernetes-client, by adding those args at runtime if they were missing. This breaks a subsequent call to `kubectl apply...` for reasons I decided not to investigate

**Comment by ffissore** [comment]
I created an issue on kubernetes-client https://github.com/godaddy/kubernetes-client/issues/573
